extraction_prompt: data/datasets/iard/user_dialogue_acts_extraction_prompt.txt

intent_labels:
  - IQU
  - CON
  - REF
  - STO
  - PRO
  - ANS
  - ASK
  - SEE
  - ACC
  - REJ
  - INQ
  - CRI-F
  - CRI-A
  - NRE
  - CRI-C
  - OTH

slot_labels:
  - GENRE
  - TITLE
  - PLOT
  - ACTOR
  - DIRECTOR
  - RATING
  - KEYWORDS
  - YEAR
  - OTHER

llm_interface:
  llm_interface_class_path: "usersimcrs.llm_interfaces.ollama_interface.OllamaLLMInterface"
  llm_interface_args:
  configuration_path: config/llm_interface/config_ollama_default.yaml
